return { -- The default theme for basalt!
    basaltBG = colors.lightGray,
    basaltFG = colors.black,
    FrameBG = colors.gray,
    FrameFG = colors.black,
    ButtonBG = colors.gray,
    ButtonFG = colors.black,
    CheckboxBG = colors.gray,
    CheckboxFG = colors.black,
    InputBG = colors.gray,
    InputFG = colors.black,
    textfieldBG = colors.gray,
    textfieldFG = colors.black,
    listBG = colors.gray,
    listFG = colors.black,
    dropdownBG = colors.gray,
    dropdownFG = colors.black,
    radioBG = colors.gray,
    radioFG = colors.black,
    selectionBG = colors.black,
    selectionFG = colors.lightGray,
}